# Railway deployment configuration
version: "3.8"

services:
  web:
    build: .
    ports:
      - "${PORT:-8001}:8001"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - PORT=${PORT:-8001}
    volumes:
      - ./data:/app/data
    restart: unless-stopped
